#!/bin/sh

sleep 1
xrandr --output HDMI-1-0 --mode 1920x1080 --rate 144 --primary
xrandr --output eDP-1 --off
#xrandr --output HDMI-2-0 --mode 1920x1080 --rate 144 --primary
#xrandr --output HDMI-2-1 --mode 1920x1080 --rate 144 --primary
#xrandr --output eDP1 --on

bspc monitor HDMI-1-0 -a 1 2 3 4 5 6 7 8 9
#bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config removal_adjustment true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config single_monocle false
bspc desktop -f next.local
bspc desktop -f next.local
bspc desktop -f next.local
bspc desktop -f next.local
bspc desktop -f next.local
bspc rule -a "*" state=tiled
export COLOR_NAV=#1C2541
export COLOR_ACC=#007C77
~/.config/polybar/scripts/get_color.sh &
~/.config/script/set_wallpaper.sh

sxhkd >>/tmp/log_nico/sxhkdrc.log 2>&1 &
compfy >>/tmp/log_nico/compfy.log 2>&1 &
polybar main >>/tmp/log_nico/polybar.log 2>&1 &
